/* game/common/fei.cpp -- RECONSTRUCTED data TU (src nfs4\GAME\COMMON\FEI.obj; sld FEL.H).
 *   DATA-ONLY: defines FEI_gList[114] (FEI_tList = {int v; int *p}) -- the FE input-binding table
 *   mapping an input value to a pointer-to-editable-global. EXT data @0x8011279c, 912 B, .data
 *   (in-image, 582/912 non-zero). v = exact nfs4-f.exe bytes; p = symbolicated to &global /
 *   (char*)&base+off (108 non-null ptrs into GameSetup_gData et al). Referenced by gmesetup.cpp.
 *   Walk-skipped (data-only, no .text); found during library/runtime inventory closure. */
#include "../../nfs4_types.h"
#include "fei_externs.h"

FEI_tList FEI_gList[114] = {   /* @0x8011279c */
  { 1, (int *)0 },
  { 3, (int *)0 },
  { 4, (int *)0 },
  { 5, (int *)0 },
  { 6, (int *)&gUseFrontend },
  { 7, (int *)&GameSetup_gData },
  { 8, (int *)((char *)&GameSetup_gData + 0x4) },
  { 9, (int *)((char *)&GameSetup_gData + 0x8) },
  { 10, (int *)((char *)&GameSetup_gData + 0xc) },
  { 11, (int *)((char *)&GameSetup_gData + 0x10) },
  { 12, (int *)((char *)&GameSetup_gData + 0x14) },
  { 13, (int *)((char *)&GameSetup_gData + 0x18) },
  { 14, (int *)((char *)&GameSetup_gData + 0x1c) },
  { 15, (int *)((char *)&GameSetup_gData + 0x20) },
  { 16, (int *)((char *)&GameSetup_gData + 0x38) },
  { 17, (int *)((char *)&GameSetup_gData + 0x5c) },
  { 18, (int *)((char *)&GameSetup_gData + 0x3c) },
  { 19, (int *)((char *)&GameSetup_gData + 0x44) },
  { 20, (int *)((char *)&GameSetup_gData + 0x48) },
  { 21, (int *)((char *)&GameSetup_gData + 0x4c) },
  { 22, (int *)((char *)&GameSetup_gData + 0x50) },
  { 23, (int *)((char *)&GameSetup_gData + 0x54) },
  { 24, (int *)((char *)&GameSetup_gData + 0x2c) },
  { 25, (int *)((char *)&GameSetup_gData + 0x30) },
  { 26, (int *)((char *)&GameSetup_gData + 0x34) },
  { 27, (int *)((char *)&GameSetup_gData + 0x58) },
  { 28, (int *)((char *)&GameSetup_gData + 0x3c4) },
  { 29, (int *)((char *)&GameSetup_gData + 0x3c8) },
  { 30, (int *)((char *)&GameSetup_gData + 0x3cc) },
  { 31, (int *)((char *)&GameSetup_gData + 0x3d0) },
  { 32, (int *)((char *)&GameSetup_gData + 0xbc) },
  { 33, (int *)((char *)&GameSetup_gData + 0xb8) },
  { 34, (int *)((char *)&GameSetup_gData + 0xc8) },
  { 35, (int *)((char *)&GameSetup_gData + 0xcc) },
  { 36, (int *)((char *)&GameSetup_gData + 0xd0) },
  { 37, (int *)((char *)&GameSetup_gData + 0x1ac) },
  { 38, (int *)((char *)&GameSetup_gData + 0x1b0) },
  { 39, (int *)((char *)&GameSetup_gData + 0xe0) },
  { 40, (int *)((char *)&GameSetup_gData + 0xe4) },
  { 41, (int *)((char *)&GameSetup_gData + 0xe8) },
  { 42, (int *)((char *)&GameSetup_gData + 0xec) },
  { 43, (int *)((char *)&GameSetup_gData + 0xf0) },
  { 44, (int *)((char *)&GameSetup_gData + 0xf4) },
  { 45, (int *)((char *)&GameSetup_gData + 0xf8) },
  { 46, (int *)((char *)&GameSetup_gData + 0xfc) },
  { 47, (int *)((char *)&GameSetup_gData + 0x100) },
  { 48, (int *)((char *)&GameSetup_gData + 0x108) },
  { 49, (int *)((char *)&GameSetup_gData + 0x104) },
  { 50, (int *)((char *)&GameSetup_gData + 0xc0) },
  { 51, (int *)((char *)&GameSetup_gData + 0xc4) },
  { 52, (int *)((char *)&GameSetup_gData + 0x60) },
  { 53, (int *)((char *)&GameSetup_gData + 0x68) },
  { 54, (int *)((char *)&GameSetup_gData + 0x70) },
  { 55, (int *)((char *)&GameSetup_gData + 0x78) },
  { 56, (int *)((char *)&GameSetup_gData + 0x80) },
  { 57, (int *)((char *)&GameSetup_gData + 0x90) },
  { 58, (int *)((char *)&GameSetup_gData + 0x88) },
  { 59, (int *)((char *)&GameSetup_gData + 0xa0) },
  { 60, (int *)((char *)&GameSetup_gData + 0x98) },
  { 61, (int *)((char *)&GameSetup_gData + 0xa8) },
  { 62, (int *)((char *)&GameSetup_gData + 0xb0) },
  { 63, (int *)((char *)&GameSetup_gData + 0x64) },
  { 64, (int *)((char *)&GameSetup_gData + 0x6c) },
  { 65, (int *)((char *)&GameSetup_gData + 0x74) },
  { 66, (int *)((char *)&GameSetup_gData + 0x7c) },
  { 67, (int *)((char *)&GameSetup_gData + 0x84) },
  { 68, (int *)((char *)&GameSetup_gData + 0x94) },
  { 69, (int *)((char *)&GameSetup_gData + 0x8c) },
  { 70, (int *)((char *)&GameSetup_gData + 0xa4) },
  { 71, (int *)((char *)&GameSetup_gData + 0x9c) },
  { 72, (int *)((char *)&GameSetup_gData + 0xac) },
  { 73, (int *)((char *)&GameSetup_gData + 0xb4) },
  { 74, (int *)((char *)&GameSetup_gData + 0x24) },
  { 76, (int *)((char *)&GameSetup_gData + 0x10c) },
  { 259, (int *)0 },
  { 260, (int *)((char *)&GameSetup_gData + 0x3d4) },
  { 261, (int *)((char *)&GameSetup_gData + 0x3d8) },
  { 262, (int *)((char *)&GameSetup_gData + 0x3dc) },
  { 263, (int *)((char *)&GameSetup_gData + 0x3ec) },
  { 264, (int *)((char *)&GameSetup_gData + 0x3f0) },
  { 265, (int *)((char *)&GameSetup_gData + 0x3f4) },
  { 266, (int *)((char *)&GameSetup_gData + 0x3e0) },
  { 267, (int *)((char *)&GameSetup_gData + 0x3e4) },
  { 268, (int *)((char *)&GameSetup_gData + 0x3e8) },
  { 269, (int *)((char *)&GameSetup_gData + 0x418) },
  { 270, (int *)((char *)&GameSetup_gData + 0x3f8) },
  { 271, (int *)((char *)&GameSetup_gData + 0x3fc) },
  { 272, (int *)((char *)&GameSetup_gData + 0x410) },
  { 273, (int *)((char *)&GameSetup_gData + 0x41c) },
  { 274, (int *)((char *)&GameSetup_gData + 0x414) },
  { 275, (int *)((char *)&GameSetup_gData + 0x40c) },
  { 276, (int *)((char *)&GameSetup_gData + 0x42c) },
  { 277, (int *)((char *)&GameSetup_gData + 0x404) },
  { 278, (int *)((char *)&GameSetup_gData + 0x408) },
  { 279, (int *)((char *)&GameSetup_gData + 0x420) },
  { 280, (int *)((char *)&GameSetup_gData + 0x424) },
  { 281, (int *)((char *)&GameSetup_gData + 0x428) },
  { 282, (int *)((char *)&GameSetup_gData + 0x444) },
  { 283, (int *)((char *)&GameSetup_gData + 0x44c) },
  { 284, (int *)((char *)&GameSetup_gData + 0x450) },
  { 285, (int *)((char *)&GameSetup_gData + 0x454) },
  { 286, (int *)((char *)&GameSetup_gData + 0x458) },
  { 287, (int *)((char *)&GameSetup_gData + 0x45c) },
  { 288, (int *)((char *)&GameSetup_gData + 0x460) },
  { 289, (int *)((char *)&GameSetup_gData + 0x464) },
  { 290, (int *)((char *)&GameSetup_gData + 0x468) },
  { 291, (int *)((char *)&GameSetup_gData + 0x46c) },
  { 292, (int *)((char *)&GameSetup_gData + 0x470) },
  { 293, (int *)((char *)&GameSetup_gData + 0x474) },
  { 294, (int *)((char *)&GameSetup_gData + 0x478) },
  { 295, (int *)((char *)&GameSetup_gData + 0x47c) },
  { 296, (int *)((char *)&GameSetup_gData + 0x480) },
  { 297, (int *)((char *)&GameSetup_gData + 0x484) },
  { 0, (int *)0 },
};
